package com.test.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "account".
 */
@Entity(nameInDb = "account")
public class Account {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private String sex;
    private String tel;
    private String address;
    private String company;
    private Integer assets_type;
    private Integer consumer_grade;
    private String card_id;
    private String flag;
    private String attribution;
    private Integer integral;

    @Generated
    public Account() {
    }

    public Account(Long id) {
        this.id = id;
    }

    @Generated
    public Account(Long id, String name, String sex, String tel, String address, String company, Integer assets_type, Integer consumer_grade, String card_id, String flag, String attribution, Integer integral) {
        this.id = id;
        this.name = name;
        this.sex = sex;
        this.tel = tel;
        this.address = address;
        this.company = company;
        this.assets_type = assets_type;
        this.consumer_grade = consumer_grade;
        this.card_id = card_id;
        this.flag = flag;
        this.attribution = attribution;
        this.integral = integral;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public Integer getAssets_type() {
        return assets_type;
    }

    public void setAssets_type(Integer assets_type) {
        this.assets_type = assets_type;
    }

    public Integer getConsumer_grade() {
        return consumer_grade;
    }

    public void setConsumer_grade(Integer consumer_grade) {
        this.consumer_grade = consumer_grade;
    }

    public String getCard_id() {
        return card_id;
    }

    public void setCard_id(String card_id) {
        this.card_id = card_id;
    }

    public String getFlag() {
        return flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    public String getAttribution() {
        return attribution;
    }

    public void setAttribution(String attribution) {
        this.attribution = attribution;
    }

    public Integer getIntegral() {
        return integral;
    }

    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

}
