package com.test.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.test.greendao.Login;
import com.test.greendao.Account;

import com.test.greendao.LoginDao;
import com.test.greendao.AccountDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginDaoConfig;
    private final DaoConfig accountDaoConfig;

    private final LoginDao loginDao;
    private final AccountDao accountDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginDaoConfig = daoConfigMap.get(LoginDao.class).clone();
        loginDaoConfig.initIdentityScope(type);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        loginDao = new LoginDao(loginDaoConfig, this);
        accountDao = new AccountDao(accountDaoConfig, this);

        registerDao(Login.class, loginDao);
        registerDao(Account.class, accountDao);
    }
    
    public void clear() {
        loginDaoConfig.clearIdentityScope();
        accountDaoConfig.clearIdentityScope();
    }

    public LoginDao getLoginDao() {
        return loginDao;
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

}
